2022-08-30 19:19:47,897 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,899 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,899 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,899 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,899 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,900 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,900 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,900 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,900 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,900 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,900 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,901 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,901 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,901 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,901 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,901 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,901 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,902 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,902 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,902 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,902 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,902 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,903 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,903 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,903 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,903 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,903 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,904 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,904 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,904 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,904 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,904 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,905 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,905 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,905 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,905 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,905 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,906 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,906 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,906 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,906 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,906 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,907 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,907 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,907 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,907 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,907 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,908 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,908 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,908 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,908 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,908 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,908 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,909 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,909 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,909 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,909 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,909 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,909 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,910 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,910 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,910 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,910 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,910 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,910 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,911 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,911 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,911 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,911 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,911 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,911 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,912 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,912 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,912 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,912 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,912 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,913 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,913 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,913 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,913 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,913 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,914 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,914 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,914 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,914 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,914 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,914 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,915 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,915 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,915 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,915 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
2022-08-30 19:19:47,915 ERROR Exception
Traceback (most recent call last):
  File "D:\Projects\Python Projects\Publisher_linkvertise\main.py", line 264, in main
    loko
NameError: name 'loko' is not defined
